name: Matrix with Node.js
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        version: ["3.10","3.9","3.8"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
         - platform: ubuntu-latest
           version: "3.6"
        exclude:
             - platform: windows-latest
               version: "3.10"
    runs-on: ${{ matrix.platform }}
    steps:
     - name: Setup Python  ${{ matrix.platform }}
       uses: actions/setup-python@v2
       with:
         python-version: {{ matrix.version }}

       
